# 应用服务 WEB 访问端口
server:
  port: 8080

rocketmq:
  name-server: localhost:9876

  producer:
    group: springbootGroup

  consumer:
    group: testGroup

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shard?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2 # 有16个数据库，默认就是0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaomi.bms.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      xiaomi.bms:
        mapper: debug
        service: info
        controller: info